name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Airdrop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Forge Build
        run: forge build

      - name: Forge Unit Test
        run: forge test -vvv

      - name: Integration test
        run: bun integration